### ISSUE TITLE
Why latest version has "location" permission?

### ISSUE THREAD

**Issue by jg777** [ligi/SurvivalManual#103]
Why does the latest version have "<uses-permission-sdk-23 android:name="android.permission.ACCESS_COARSE_LOCATION" />" in the AndroidManifest.xml? This offline app should never need this permission. Please fix this.

**Comment by ligi** [comment]
I think this permission is also in older versions. My thinking was that I want to offer local content. Adding permissions later can be problematic. Also you do not have to grant it with runtime permissions
