### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [ligi/SurvivalManual#157]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by Korb** [comment]
Screenshots on app page still missing:
![Screenshot_2023_0327_224752](https://user-images.githubusercontent.com/3509797/228050567-960891b5-6d46-4a8b-aba1-76a020cd7213.jpg)

**Comment by Korb** [comment]
Related to #276
