### ISSUE TITLE
Add chapter on how to create power

### ISSUE THREAD

**Issue by ligi** [ligi/SurvivalManual#17]

**Comment by ligi** [comment]
Section can also be broader and cover basic electronic knowledge and instructions on how to repair stuff

**Comment by Alpha402** [comment]
Possibly include a basic instruction set on creating a small hand crank or bicycle powered DC motor 5V generator to charge small devices such as cell phones, rechargeable battery packs, flash lights, etc. 

Include the importance of redundancy when it comes to power generation ranging from solar chargers, external battery packs, hand crank generators, etc.

**Comment by ligi** [comment]
started here: https://github.com/ligi/SurvivalManual/wiki/Power
