### ISSUE TITLE
Some possible enhancements

### ISSUE THREAD

**Issue by DrakoDrakkonis** [ligi/SurvivalManual#19]
I think very successful to have an application like this, but - given that I know the publication in PDF format distributed by the DoD, I have doubts if it is or not advisable as it is ( Personally, I think that an interactive ePub would be most appropriate for the case ).

	Anyway, here are my suggestions:

	1. I have  '**Survival Manual 1.7**’ in a 10.1 tablet, and even so the text font is extremely small. I can read it, but there will be users who cannot do it. If so, why not include tools for text zoom?

	2 ‘**Survival Manual**’ is displayed by default to the width of my tablet, and is rather boring to have to go its menu to use the screen rotation button. Would be possible to include it in the bar of SM?

	3. I am not a specialist in Botany, but  Asparagus (_Asparagus officinalis_),  Bamboo (_Bambusa_),  Cashew nut (_Anacardium occidentale_), Banana and Plantain (Musa species), and Amaranth (_Amaranthus_ species) that I know does not correspond or poorly correspond with the images included in **Edible / Medicine Plants** of  **SM**. It is obvious that it is not your fault but the Army Editors who worked in the Official Guide that you used for the application. Is there any way that you can consult with a specialist?

I also think that **SM**, to be based on a public domain source, could be changed and include images and graphics more up-to-date and appropriate from **Creative Commons** and **Wikimedia Commons**.

4. I think successful having accepted the request for the ‘**Share**’ button on the toolbar of **SM**, and it seems to me that it would be much better if the user could copy text and images of the contents. Would it be possible to include this tool, also?

It's all for now.

Greetings and thank you very much for your kind attention.

**PS /** To the people that are complaining about of the militarized content of **SM**: The author of this application is honourable to the manifest what is source of information of him: _There are that accept this made such as it is._ If you want something less militarized, best thing is to go to the **EPA** site. This federal bureau offers in its repository a wide range of information and digitized guides aimed at citizens and communities in general, so that they face and learn to  solve the impact of state of emergency and natural disasters that may occur at any time.

**Comment by ligi** [comment]
hui - this is a lot - better open single tickets for issues - makes it easier to process:
 to 1 - you can change the font-size in your system - this will affect SurvivalManual as I use TextView with unit sp
to 2 - do you see this pattern at other apps? Not really - and IMHO this is a good thing ;-)
to 3/4/PS - everyone can change the content - I converted it to a wiki - the army stuff was just the base and I hope will be gone/reworked over time - everyone can change and invite specialists - and then change like: https://github.com/ligi/SurvivalManual/wiki/b/_compare/63757c05b074ba455ca90cd2a2d6699e1ef464d4...36d6173b1287f45d5a6f3516467f8186205cd9a8
Also happy if people put info from EPA or other sources in there ( if the license is OK to do so ) - but I rather keep on coding and hope the content work will come from users
