### ISSUE TITLE
Specific licensing for the content

### ISSUE THREAD

**Issue by inferno986return** [ligi/SurvivalManual#206]
I am working on an e-book and an eventual printable version of this survival manual.

I'm not sure though what licence covers the text and image content in the wiki. I can see there's a GPLv3 and a BSD-like licence for the app.

Is the content licenced under BSD-like licencing or would a Creative Commons licence be more appropriate?

**Comment by ligi** [comment]
Unfortunately this is not possible - should have done so from the beginning beginning - but it is not really my topic - I know how to deal with it for software - but not for content.  But setting it now would be "re-licensing" as there are multiple contributors - so content will just be as-is public domain.

**Comment by inferno986return** [comment]
Thanks for clarifying at least. I'll put that in the e-book project's ReadMe and indicia.
