### ISSUE TITLE
stop identifying deadly plants as edible

### ISSUE THREAD

**Issue by jtracey** [ligi/SurvivalManual#21]
The images for deadly and edible plants are currently the same. For example, the image for "canna lilly" is actually the image for poison hemlock, and describes it as having an edible root. Poison hemlock's roots look like wild carrot (Q.A.L.), and a single bite is enough to kill just about anyone.

While I'll leave the title as referring to just this particular problem, a fuckup this big makes me think you aren't qualified to create this app, and I would rather you take it down entirely. I seriously doubt this is the only problem, as I'm not exactly an expert in this field, yet spotted the issue within seconds of installing. As of right now, a person is more likely to die if they used this app than if they didn't have it.

**Comment by ligi** [comment]
I do not do the content - just the code - the content is from the army: http://www.survivalebooks.com/survivalfm3-0570.html

**Comment by jtracey** [comment]
That's not "the army," that's some random website. Just because they say it's from the army doesn't mean it's accurate. Seriously, look for yourself:
look at "Poison hemlock": http://www.survivalebooks.com/c.htm
look at "Canna lilly": http://www.survivalebooks.com/b.htm
Same photo. Ultimately, I don't really care where the information came from, it's immediately obvious to anyone who has even a little background that it's wrong, and in what is literally the worst conceivable way possible (people *will die* if they follow its advice, poison hemlock is extremely common everywhere). If you don't do something about this, I'm going to just go notify Google and F-Droid.

**Comment by ligi** [comment]
I am open to discuss this - please wait with notifying Google and Fdroid. This content is used in a lot of places and originated in an army manual.  Please if you inform somebody also do this for all others - at least in my app it is possible to change this:

https://play.google.com/store/apps/details?id=com.max.SurvivalGuide
https://play.google.com/store/apps/details?id=com.androidtrainer.survive

**Comment by jtracey** [comment]
Arrrgh ok. I'll try to contact the people who run that site. What a mess...

**Comment by ligi** [comment]
thanks for the info - I will remove the plant with the error you pointed out ( thanks for that ) - but I will leave the app online as here we are able to change and correct things - also I will add a big warning that the content needs some careful eyes

**Comment by jtracey** [comment]
Sorry, let me clarify: ALL of the edible plants use the wrong images, from the dangerous plants section. I pointed out poison hemlock because it's the easiest case to see the problem (pervasive, easily identifiable, obviously not a lily, deadly if eaten).

**Comment by ligi** [comment]
I removed section c for now until these errors get corrected - thanks for the feedback - let me know when you get feedback from the website
