### ISSUE TITLE
Add Morse Code chart from Wikipedia to Apps chapter

### ISSUE THREAD

**Issue by inferno986return** [ligi/SurvivalManual#231]
Wikipedia has a nice and simple Morse Code chart which I have adapted into my own e-book of the Survival Guide under the Morse Code heading in the Apps chapter.

Wouldn't it be easier to just use Wikipedia's own SVG which is in the public domain? https://en.wikipedia.org/wiki/File:International_Morse_Code.svg

What do you think?

**Comment by vkuehn** [comment]
how about add text to morse functionality to the app ?

**Comment by mgroves** [comment]
I was surprised that a Morse code chart wasn't already in the app someplace.

**Comment by inferno986return** [comment]
> I was surprised that a Morse code chart wasn't already in the app someplace.

I already added it as a column to my e-book adaptation of the app. I should add it to the upstream too.

**Comment by inferno986return** [comment]
I've just added the Morse code to the new NATO phonetic alphabet table in Signalling. It takes up far less space than the original separate table I made in my e-book adaptation for the Apps chapter.

**Comment by mgroves** [comment]
This hasn't shown up in the Android app yet. Any idea when that will happen?
