### ISSUE TITLE
Fig 9-7 not formatted

### ISSUE THREAD

**Issue by Siltaar** [ligi/SurvivalManual#25]
I just went to check the wiki but found no explanation why the list of fig 9-7 is badly displayed in version 2.6.

**Comment by ligi** [comment]
that should fix it: https://github.com/ligi/SurvivalManual/wiki/09/_compare/932d142ad7c58df90bf3ec7c4314c5994cbad675...0d5606962e77c9ad0d8ec5fe62b6b5b410dd7839
change will be included in 2.7 - thanks for reporting
