### ISSUE TITLE
Crash when following a link; unable to restart till app data cleared

### ISSUE THREAD

**Issue by trmusson** [ligi/SurvivalManual#26]
Steps to repeat:
1. Visit "Fish and Mollusks" in the Appendix.
2. At the bottom of the page, under the "Fish with Toxic Flesh" heading, follow the link to Figure 8-2.
3. For me, the app dies with the "Unfortunately, Survival Manual has stopped" pop up.
4. The app won't open again until its data is cleared via Android settings.

I'm using Survival Manual V2.6 on Android 6.0.1

I love the app - thanks for your work :)

**Comment by ligi** [comment]
Thanks for reporting and the nice steps to reporduce!
