### ISSUE TITLE
Google Play Store 

### ISSUE THREAD

**Issue by cowboydaniel** [ligi/SurvivalManual#288]
I've noticed this isn't available on the Google Play Store anymore. What needs to be done to get it back up on there?

**Comment by cwangsanata** [comment]
Seconded. Maybe an APK release would be beneficial too.

**Comment by jank04** [comment]
Ye same. I wanted to install it on my new phone but unfortunately this app is no longer in Playstore. Could you please put the latest APK into releases?

**Comment by ligi** [comment]
I uploaded 5.0.0 to google play beta testing and the github releases. Should also soon appear on f-droid.
Please let me know if everything works for you all so I can roll it out more widely.
