### ISSUE TITLE
Scrolling up is buggy

### ISSUE THREAD

**Issue by pschfr** [ligi/SurvivalManual#35]
When scrolling up when you're at the top, the app tries to hide the navbar, but immediately makes it jump back down in. This happens when scrolling up anywhere, but it's just most obvious at the top.

**Comment by ligi** [comment]
Please join the beta - just in the process of uploading 3.0 which should fix the problem - if it does not do it for you please let me know

**Comment by pschfr** [comment]
What is the link to join the beta? I cannot find it.

**Comment by ligi** [comment]
https://play.google.com/apps/testing/org.ligi.survivalmanual

currently uploading the beta

**Comment by pschfr** [comment]
I can confirm the bug doesn't exist anymore! Keep up the good work!

**Comment by ligi** [comment]
thanks for the feedback! much appreciated
