### ISSUE TITLE
Make content translatable

### ISSUE THREAD

**Issue by Peuc** [ligi/SurvivalManual#4]
Thanks for this application that provides a lot of valuable information that should be available to everyone!
Since I guess there is no official translation for this content, what about adding multiple languages, and some way to create community driven translations?

**Comment by ligi** [comment]
thanks - yes I was also thinking about that - not yet sure about the right approach. Was thinking about making a wiki-like thingy from the whole thing to attack #2 and translation / extension

**Comment by Peuc** [comment]
Since the book is in public domain, you may consider putting it on Wikibooks or Wikisource so we can rely on Wikimedia community to help in the translation effort.
Another solution may be to use Transifex (nonfree).

**Comment by ligi** [comment]
I can use transifex for free as an open-source program - but transifex
for these long strings is no good.

**Comment by Peuc** [comment]
Sure, I just meant by choosing Transifex you then depend on non free (as free speech) software as a service. Anyway, Wiki* projects are probably better solution in this case.

**Comment by ligi** [comment]
ah all right - true was also thinking a wiki might be better. Will have to convert html->markdown first

**Comment by ligi** [comment]
I started to convert to markdown - as this needs some manual work anyway I am combining this with #2 and a general cleanup. Currently I am doing it in the github wiki of this project - but this will have to move for translating later on. But I think editing of markdonwn/translatin I will do in the app then. You can find ( and help ) it here:

https://github.com/ligi/SurvivalManual/wiki

currently using ghe following online tools: http://domchristie.github.io/to-markdown/ for the rough convert and  http://markdownlivepreview.com/ for preview. Help would be very welcome !-)

**Comment by ligi** [comment]
btw it seems possible that we can make the translations in the github wiki - subdirs are now supported as it seems and we can just do a subdirectory for each language.

**Comment by Peuc** [comment]
I just done monkey convert from html to markdown all pages from 05 to g, with Home - no additional cleanup. What about I push it so we can use it as a basis prior to cleanup?

**Comment by ligi** [comment]
:1

**Comment by Peuc** [comment]
Can you please grant me write access to the wiki so I can push?

**Comment by ligi** [comment]
just invited you as collaborator for this project

**Comment by ligi** [comment]
thanks! I just opened the wiki for everyone

**Comment by Peuc** [comment]
Looks like something went wrong: I can edit wiki content with online interface, but I cannot push content from git anymore. Can you please check this?

**Comment by ligi** [comment]
I had to do a bit of risk assessment. Now I protected the master-branch and gave you back the rights.

**Comment by Peuc** [comment]
Works, thanks.

**Comment by ligi** [comment]
I released a initial version that is backed by markdown as 1.2 to beta
