### ISSUE TITLE
v3.2 missing in F-Droid Store

### ISSUE THREAD

**Issue by Krawei** [ligi/SurvivalManual#42]
When I take a look in the playstore I notice, that "SurvivalManual" current version is v3.2. In the F-Droid store the current version is v2.8 .

What's the reason for the different versions? Is this Github-project still alive?

Kind Regards,

Krawei

**Comment by ligi** [comment]
This is a fdroid problem - please see:

https://forum.f-droid.org/t/survival-manual/138

Nothing really I can do so closing this issue. And yes the Github-project is still alive!-) Survival Inception ..

**Comment by ligi** [comment]
FYI: 3.2 is now on FDroid
