### ISSUE TITLE
New chapters contrast with the rest of the book

### ISSUE THREAD

**Issue by Siltaar** [ligi/SurvivalManual#45]
Hi,

Being fan of the book, I don't like the "day to day discussion" approach of new chapters.
The books was about how to survive, and it becomes "what you should or could have done to prepare".

**Before it was :** here is how to actually make soap, step by step.
**Now it is :** you just have to make some electronics to have your wind turbine working.
See the difference ? It's not the same empowering book, it's "you should have chose better studies".

Still, I completed the MultiTool chapter to present a viable alternative to Leatherman (having enough practice with Victorinox' SwissTool Spirit). Here also, the book becomes an inventory of things to buy before. And I strongly disagree with adding YouTube links in the book (in addition to the "I tell my life" tone…).

Sorry I'm harsh, but I'm still shocked in fact :-p

Still, I hope it won't disqualify me from the coming proof readers list !

(I'm going to suggest content in Apps part (at least Wikipedia Offline apps), and Power (maybe lemon, copper and zinc approach…)).

**Comment by ligi** [comment]
I added the power section and I know it is not complete and needs a lot of more work. Step by step instructions here would be good. But since doing so the comments "I will not have power on my phone in this situation" where drastically reduced and the rest I could point there. So it kinda works for me and I will not remove it. That said I am happy about additions/changes in this area.

**Comment by ligi** [comment]
Was just reading the MultiTool part - this sounds really wrong:

"NASA did even studied and make its own Swiss Army like Tool to bring in space stations."

also do you have a source for this?

**Comment by Siltaar** [comment]
Maybe a thing that sounded bad was my confusion between Swiss Army Knife and MultiTools (as I was speaking about a MultiTool make by a Swiss Army Knife provider). I tried to fix it.

**Comment by Siltaar** [comment]
Here are two of the three 1st links for : https://duckduckgo.com/?q=nasa+swiss+army+knife&t=ffab&ia=web

Swiss Army Knife: 

> The Swiss Army knife has been present in space missions carried out by NASA since the late 1970s. In 1978, NASA sent a letter of confirmation to Victorinox regarding a purchase of 50 knives known as the Master Craftsman model. In 1985, Edward M. Payton, brother of astronaut Gary E. Payton, sent a letter to Victorinox, asking about getting a Master Craftsman knife after seeing the one his brother used in space. There are other stories as well of repairs conducted in space using a Swiss Army knife.

https://en.wikipedia.org/wiki/Swiss_Army_knife

Victorinox Space Shuttle Swiss Army Knife:

> The Space Shuttle Swiss Army knife is a limited production knife that includes an inlaid image of the Space Shuttle. This model was first available in the mid-1980's (model #5049), and it was retired in 1990.

https://www.smartknives.com/Victorinox-Knives/Victorinox-Space-Shuttle.htm
