### ISSUE TITLE
Proof read augmented Apps chapter

### ISSUE THREAD

**Issue by Siltaar** [ligi/SurvivalManual#46]
I spent a couple of hours to transcript in the Apps chapter my experience and center of interest in this area (I'm not stumble uppon SurvivalManual by mistake ^_^).

213 additions did at least double the size of the document. Mainly with links to example of mention apps, and new parts (Radio, Morse signal, offline encyclopedia…).

It may still require a proof reading.

Else, I suggest we remove the Cryptocurrency part, as being less pertinent than the rest from my point of view and would drive a skeptical reader away from this nonetheless interesting book. The point about cryptocurrency is to prepare for a somewhat post-apocaliptical world, and not a plane-crash survival scenario. Post-apocaliptical or post-petroleum transition is a matter which deserves it own book I think.

To finish, I added mention of the author of Tea Time and Pass apps, which are not exactly as pertinent as the rest, but add some humour to the content (which is the think I'm missing reading this book; under 20% of humour, it's proven that a message is less understood by its human receiver).

**Comment by ligi** [comment]
Thanks for your changes! Just had a quick read and in general I like it - but we have to change:

 "Every Android phone is delivered with an FM radio receiver."

this is just not true. 
Also I want to keep the cryptocurrency part for personal reasons. 
Will have a deeper read later with some time.
Can you also please add yourself to the credits section?

**Comment by Siltaar** [comment]
I did fix my absolutism about Radios in Android phones.

**Comment by Siltaar** [comment]
I humbly added my myself to the credit section.

**Comment by Siltaar** [comment]
>  Also I want to keep the cryptocurrency part for personal reasons.

Let me guess, you will call for BitCoin donations ?

**Comment by ligi** [comment]
No but I think they are important to survive in the future when banks will fail and we hopefully do not spend money to rescue them anymore ..

**Comment by Siltaar** [comment]
Ok, so it's a post-petroleum transition scenario.

**Comment by ligi** [comment]
Not sure about the timing - and to be honest it is also a bit because I know and respect @schildbach - the author of the bitcoin app I mention there ..

**Comment by Siltaar** [comment]
Added Barcode scanner app.
I can't tell about xzing, not found in f-droid.org

**Comment by ligi** [comment]
Just got home and checked the changes a bit more - two things:
 - please a max heading depth of 3 so # ## or ### - no ####
 - please no abitrary urls where I do not know how stable they are - means thinks like wikipedia or youtube is ok - not the victoriniox one

**Comment by Siltaar** [comment]
Linked to #14 closing this one.
