### ISSUE TITLE
Proof read augmented Power chapter

### ISSUE THREAD

**Issue by Siltaar** [ligi/SurvivalManual#47]
I did add a lemon electric pile part, and ciphers about solar panels, and a MultiTool link, some car considerations and power-bank batteries maintenance advices. Also smartphone powersaving tricks.
(edit: 260 additions and 48 deletions)

**Comment by ligi** [comment]
Thanks - was just reading it - to be honest I am not yet sure about the usefulness of lemon-batteries in a survival situation - but I will keep it in there as it still teaches things ..
