### ISSUE TITLE
Add (at least a mention of) Hugh Piggott "hand made" wind turbines in Power section

### ISSUE THREAD

**Issue by Siltaar** [ligi/SurvivalManual#48]
The blog : http://scoraigwind.co.uk/
Old looking home page : http://www.scoraigwind.com/

I know this concept because of adult-schools (in France) all accross the country teaching to groups how to make some.

3000 Watt is not rare for such engines.

**Comment by ligi** [comment]
Sounds great!

**Comment by Siltaar** [comment]
Done.
