### ISSUE TITLE
Set colorPrimaryDark following the Material Design Color Guidelines

### ISSUE THREAD

**Issue by marco97pa** [ligi/SurvivalManual#50]
Actually the app has a __bad colorPrimaryDark color__ . It does not respect colorPrimary, it seems more bright than it should be.

Google has made a tool to set the correct color of the app, following the Material Design. You can visit it: https://material.io/guidelines/style/color.html

**Comment by ligi** [comment]
I see your point - but I am not yet sure if I should change it.
