### ISSUE TITLE
When you are in a raft and see sharks […] Bury all dead as soon as possible.

### ISSUE THREAD

**Issue by Siltaar** [ligi/SurvivalManual#53]
In Sea chapter:

> When you are in a raft and see sharks:
>  - […]
>  -   Bury all dead as soon as possible. If there are many sharks in the area, conduct the burial at night.

Is it possible to "bury" dead people while on a raft in the sea ? Maybe the verb "dispose of" is fitting more adequately here ?

**Comment by aintscurrdscars** [comment]
Technically, in maritime tradition disposing of human remains is referred to as a "burial at sea." The term "bury/burial" is adequate, and, time allowing, may include a verbose eulogy, a quick and unceremonious release into the blue (especially with the aforementioned shark issue), or a simple "Bye, Jeff."

**Comment by Siltaar** [comment]
There is no evident reference of land or earth in the bury verb, while the french translation litteraly means : put into the earth-ground. So I see my understanding mistake now, thank you.
