### ISSUE TITLE
UninitializedPropertyAccessException: lateinit property textInput has not been initialized

### ISSUE THREAD

**Issue by johnjohndoe** [ligi/SurvivalManual#54]
When I freshly build, install and run the project on a device the following error occurs:

``` java
kotlin.UninitializedPropertyAccessException: 
    lateinit property textInput has not been initialized
 at org.ligi.survivalmanual.ui.MainActivity.switchMode(MainActivity.kt:329)
 at org.ligi.survivalmanual.ui.MainActivity$onCreate$2.run(MainActivity.kt:117)
 at android.os.Handler.handleCallback(Handler.java:739)
 ...
```

I can reproduce the error on two different phones.

**Comment by ligi** [comment]
Please do a git submodule init/update - the content is not there

**Comment by johnjohndoe** [comment]
Thanks for the clarification. You might want to mention this in the developer instructions for novice devs like me.

**Comment by ligi** [comment]
you are right - should do this - hence I left this issue open - that
said - I also accept PRs ;-)

**Comment by YashwinL** [comment]
i am facing this same problem in this app, since i am beginner i don't know how to do git submodule init/update, please help me!

**Comment by johnjohndoe** [comment]
@YashwinL After **initially cloning** the repository or **pulling** a new state you need to execute the following commands in the root directory of the project:

``` bash
$ git submodule init
$ git submodule update
```

Find more information by executing `git help submodule`.
