### ISSUE TITLE
kotlin.UninitializedPropertyAccessException: lateinit property textInput has not been initialized

### ISSUE THREAD

**Issue by qyihu** [ligi/SurvivalManual#56]
Hello, I am a novice. Is learning your application, I started the application when the newspaper reported such a mistake, can help look at what is the reason? Looking forward to your recovery, please!

> kotlin.UninitializedPropertyAccessException: lateinit property textInput has not been initialized

**Comment by ligi** [comment]
You have to do a git submodule update after checkout

**Comment by qyihu** [comment]
In your help to find a solution, very grateful.
