### ISSUE TITLE
tables and warning are wider than the screen

### ISSUE THREAD

**Issue by davidak** [ligi/SurvivalManual#6]
could be fixed with conversion to markdown.

![screenshot_2016-09-25-00-49-50](https://cloud.githubusercontent.com/assets/91113/18811754/54913064-82bb-11e6-855e-d526a4b55c75.png)

Fairphone 2
1080 × 1920 pixels
https://shop.fairphone.com/en/?___store=en

---

thanks for putting this on F-Droid, could be helpful one day

**Comment by ligi** [comment]
Thanks - yes this will be fixed by converting to markdown

**Comment by ligi** [comment]
I released  a initial version that is backed by markdown as 1.2 to beta
Warnings / Tables now look like this:
![device-2016-09-26-154844](https://cloud.githubusercontent.com/assets/111600/18836529/b802cf72-8400-11e6-871b-f7ceed59f3bf.png)
