### ISSUE TITLE
Possibly incorrect versionName ("40" instead of "4.0")

### ISSUE THREAD

**Issue by veox** [ligi/SurvivalManual#60]
It seems a dot went missing in commit https://github.com/ligi/SurvivalManual/commit/82465eb1153195cb0e97452e80b1265e2ac0c09b.

On F-Droid, the proposed update is now 3.9 -> 40.

**Comment by ligi** [comment]
@veox thanks! can't really fix this for 4.0 (aka 40 ) - but will release 4.1 soon where I don't forget the dot ;-)
