### ISSUE TITLE
Add Map

### ISSUE THREAD

**Issue by Computer-Genuis** [ligi/SurvivalManual#63]
Maybe this could use google maps to display a offline map of your surroundings.

**Comment by Woile** [comment]
There are already offline map apps. Like `HERE`.

**Comment by ligi** [comment]
Thanks for the suggestion. But I would love to not make this app heavier by adding functions like this. I think it makes more sense as a separate app. I link to OSMand in the Apps chapter and think people should install a specialized app for these cases.
For what I would add some kind of maps functionality (not google-maps though I think) - would be to mark that certain data is only relevant in regions (like animals or plants that only live in a certain area)
