### ISSUE TITLE
App crashes when running in emulator | Android Studio

### ISSUE THREAD

**Issue by AbanoubG** [ligi/SurvivalManual#65]
Is there any reason why the app crashes when I download this project and import it into Android Studio? I don't change anything however when I try to run it in the emulator it crashes. The same thing if I build an APK and sideload it to my phone. Any ideas?

It builds successfully (only warns of unused event parameters) and then crashes on both the device and emulator. Android 8.1 Google Pixel

**Comment by ligi** [comment]
Did you run "git submodules update" ? Pretty sure it is this - so closing this issue - feel free to reopen if you still have an issue afterwards
