### ISSUE TITLE
Target Android O

### ISSUE THREAD

**Issue by WillieCubed** [ligi/SurvivalManual#67]
The app should target Android O to provide some minor enhancements:

- Support [adaptive icons](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html) to increase compatibility of app between devices
- Add [app shortcuts](https://developer.android.com/guide/topics/ui/shortcuts.html) for important sections to allow quick access to potentially useful information.

I'm willing to open a PR if there aren't any objections.

**Comment by cyber199** [comment]
So long as the use of adaptive icons won't break the app for launchers that don't support them or people that don't like them, I wouldn't oppose this.

**Comment by TheCraftKid** [comment]
For the adaptive icon, there's also the option to design one that is more elegant than simply putting the existing one onto a white background. I like the material app icon, but it could be optimized. Any thoughts on a tweaked adaptive icon design?

**Comment by ligi** [comment]
tbh. I played a bit with adaptive icons - and really dislike them so far .. one reason I do not yet target O ..

**Comment by TheCraftKid** [comment]
Just a question - why does Survival Manual use Firebase? It seems a little odd for an offline-oriented app. 😄

**Comment by ligi** [comment]
Offline just means that you can use it offline without any problem - this is often missunderstood - not sure how I can communicate this better.
My plan for firebase was to have collaborative editing - but did not yet find time to really do this.

**Comment by TheCraftKid** [comment]
That actually sounds pretty cool. Maybe that'll be for another update. 😉

**Comment by ligi** [comment]
we are targeting 0 now
