### ISSUE TITLE
In the section Power > Batteries > Lithium Cell, the word "the decay"

### ISSUE THREAD

**Issue by jaganshieicen** [ligi/SurvivalManual#74]
Actual behavior:
In the fourth sentence - The decay very slowly

Expected behavior: They decay very slowly

**Comment by ligi** [comment]
Thanks - fixed https://github.com/ligi/SurvivalManual/wiki/Power/_compare/9535877f8154cf0e8b31ffaa1675e8961cd8bd96...22614c75585eddb8f29599ac2d411ccaeed800d5
