### ISSUE TITLE
What does 550 mean?

### ISSUE THREAD

**Issue by jaganshieicen** [ligi/SurvivalManual#75]
Steps:
In Kits section > Shelter

Actual behavior:
550 is listed as example for shelter

Expected behavior:
Please be specific like thermal survival shelter tent paracord 550

**Comment by ligi** [comment]
Thanks - you are right - unfortunately I am quite busy right now so I cannot fix it now - would do it later - but you can also edit in the wiki if you want

**Comment by jaganshieicen** [comment]
hi ligi, I will try to edit the wiki later tonight after my dayshift work.

**Comment by jaganshieicen** [comment]
Made some modification.

Link: 
https://github.com/ligi/SurvivalManual/wiki/Kits
Screenshot:
![image](https://user-images.githubusercontent.com/25298722/39990777-1131df24-57a0-11e8-9788-73134334ac89.png)

**Comment by jaganshieicen** [comment]
Please advise before closing this issue. Thanks.

**Comment by ligi** [comment]
Thanks! looks good  - closing
