### ISSUE TITLE
The app cannot be found on app store

### ISSUE THREAD

**Issue by spiko** [ligi/SurvivalManual#82]
I get 'item not found' when clicking the link.

**Comment by ligi** [comment]
Yes there is currently a problem with google-play. You can still find the app on f-droid though. Will also try to get it back an play also soon

**Comment by aaronth07** [comment]
Still not up. Is there a way to get automatic updates without Google Play?

**Comment by jakob1379** [comment]
You can install f-droid (an app store for true open source apps only)

**Comment by aaronth07** [comment]
Still doesn't fix the issue of it not being on the play store, and not everyone wants to install another app just for this app. That also doesn't mention that this app is supposed to be a very low size, and F-Droid takes up another 20MB of storage.

**Comment by jakob1379** [comment]
I just answered your question "Is there a way to get automatic updates without Google Play?". Otherwise the answer would be to set up a little program to fetch the git, compile and install whenever repo is updated and delete files after installation, that way you might even get updates before gplay

**Comment by aaronth07** [comment]
I see, well that still doesn't fix the Play Store issue.

**Comment by ligi** [comment]
The app is back in the play store
