### ISSUE TITLE
Several suggestions I would like to help with...

### ISSUE THREAD

**Issue by smbanks80** [ligi/SurvivalManual#95]
NOTE

GitHub rules/guidelines say that we are supposed to note why we have edited a comment, so here I go...

I edited the comment below shortly after I posted it because I viewed the Survival Manual on GitHib for the first time & realized that, contrary to the way the app displays the Survival Manual on my phone, it is formatted beautifully, therefore, I deleted one of my suggestions  below because it was no longer relevant. I attempted to edit the Survival Manual on my phone so it would be easier to read, but the app wouldn't save the changes & I don't know why that is. I thought becoming a beta tester through Google Play might help but it did not. Thankfully, my search for answers led me to here & I am looking forward to being a part of this online community. Thank you! 
__________

Hello!

(This is only my 2nd post. Please bear with me, as I am new to GitHub.) I'm reaching out because I am a big fan of the Survival Manual & feel as if I can make a meaningful contribution to it due to my background knowledge, experience & writing/editing skills - all of which I'd be happy to share upon request.

I would like to make a few minor edits to the text, so that important information & instructions will be a bit more direct and concise. This would make it easier for a wide range of readers/ability levels and English Language Learners (including children) to understand. 

Children play a critical role in survival situations, as well as adults, so it is important for them to be able to access the basic information within the Survival Manual. Kids can do tremendous things when called to action. However big their hearts & creative their minds, leadership is a determing factor in their ability to succeed. When leadership fails in a survival situation, this guide may be all they have - not just to save themselves but to save the lives of those around them - so I feel it is incredibly important to consider them in the creation of this book.

As an Educator/Writer, with a background in Psychology/Pre-Med, I have worked with a variety of students with mild to moderate special needs and would be happy to contribute to the Survival Manual in this way. I could even write a small paragraph for kids at the top of each page that sums-up the main idea & lists a few key points.

Now that I think about it, adults would appreciate this concept as well. My husband is a combat veteran with service-connected PTSD. I've seen what prolonged periods of extreme stress, coupled with inadequate rest/nutrition can do to a person & I wouldn't wish it on anyone. A person's mental & physical health can dramatically decline within these kinds of circumstances & a good percentage of adults might find themselves being unable to focus on reading extensive pieces of information during those times, so perhaps summing up the main idea with a few key points at the top of each page would be a good idea for everyone.

Thank you for your time. I hope to hear back from someone soon, as I am very excited about this project!

**Comment by ligi** [comment]
Thanks for your post. The whole project is a wiki you can edit here:
https://github.com/ligi/survivalmanual/wiki
