### ISSUE TITLE
[Request] Download PDF Format (For all devices)

### ISSUE THREAD

**Issue by grravity** [ligi/SurvivalManual#96]
Highly suggesting the ability to download the manual in PDF and a variety of other formats to store on multiple devices, in case one loses their phone, battery dies, etc. in the case of a situation, this would be extremely important and helpful.

**Comment by ligi** [comment]
In the latest version you can print the whole content as PDF - isn't this what you want?

**Comment by grravity** [comment]
Download as a pdf to my device? Was suggesting making it so you can do so from laptop or computer from a website like your github, instead of needing to download as pdf to phone, then transfer to all other devices

**Comment by rzr** [comment]
Relate to:
https://github.com/ligi/SurvivalManual/issues/98

**Comment by ligi** [comment]
closing as this is out of scope for this project - you can generate a PDF inside the app - this is all I want to do. If someone wants to publish this PDF: feel free - but it won't be me

**Comment by rzr** [comment]
I still wish it would be nice to generate document from sources on a regular linux system.
May I ask where  contents are coming from ?  Is it published anywhere else ?

**Comment by ligi** [comment]
you can find it erher: https://github.com/ligi/SurvivalManual/wiki
